const TYPE_CHARACTERISTIC = {
    PROFESSION: 'PROFESSION',
    HEALTH: 'HEALTH',
    HOBBY: 'HOBBY',
    PHOBIA: 'PHOBIA',
    EDUCATION: 'EDUCATION',
    SKILL: 'SKILL',
    AGE: 'AGE'
}

exports.TYPE_CHARACTERISTIC = TYPE_CHARACTERISTIC